version: "3"
services:
  url-shorter:
    build: .
    ports:
      - 8080:8080
    container_name: url-shorter-api
    networks:
      - url-shorter
    entrypoint: './main'
    environment:
      - GIN_MODE=release
    depends_on:
      - url-shorter-db

  url-shorter-db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - url-shorter
    container_name: url-shorter-db
    environment:
      - POSTGRES_DB=url
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /database:/var/lib/postgresql

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    container_name: enshorter-grafana
    networks:
    - url-shorter
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: enshorter-prometheus
    networks:
      - url-shorter

networks:
  url-shorter:
    driver: bridge